services:
  synapse_db:
    image: postgres:14-alpine
    container_name: synapse_db
    restart: always
    networks:
      - synapse_network
    environment:
      - POSTGRES_USER=${SYNAPSE_DB_USER}
      - POSTGRES_PASSWORD=${SYNAPSE_DB_PASSWORD}
      - POSTGRES_DB=${SYNAPSE_DB_NAME}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ${SYNAPSE_DB_PATH}:/var/lib/postgresql/data

  coturn:
    image: coturn/coturn:latest
    container_name: synapse_turn
    restart: always
    networks:
      - synapse_network
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "5349:5349/tcp"
      - "5349:5349/udp"
      - "49152-49600:49152-49600/udp"
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
      - /home/app/synapse_chat/nginx/certbot/live/family.guilledev.com/:/certs
    command: ["-c", "/etc/coturn/turnserver.conf"]

  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse_chat
    restart: always
    networks:
      - synapse_network
    depends_on:
      - synapse_db
      - coturn
    ports:
      - "127.0.0.1:8008:8008"
    volumes:
      - ${SYNAPSE_DATA_PATH}:/data
    environment:
      - SYNAPSE_SERVER_NAME=family.guilledev.com
      - SYNAPSE_REPORT_STATS=no

  synapse_web:
    image: vectorim/element-web:latest
    container_name: synapse_web
    restart: always
    networks:
      - synapse_network
    ports:
      - "127.0.0.1:9271:80"
    volumes:
      - ./element-config.json:/app/config.json

networks:
  synapse_network:
