services:
  synapse_jwt:
    image: ghcr.io/element-hq/lk-jwt-service:latest
    container_name: synapse_jwt
    hostname: auth-server
    networks:
      - synapse_network
    environment:
      - LIVEKIT_JWT_BIND=:8080
      - LIVEKIT_URL=wss://family-server.guilledev.com/livekit/sfu
      - LIVEKIT_KEY=devkey
      - LIVEKIT_SECRET=qqobOyLBdABMWvCggZHJluiV2xYFI8eSPOAjGf4wCcTo5C09Yp5ojUDAefKvM8hn
      - LIVEKIT_FULL_ACCESS_HOMESERVERS=family-server.guilledev.com
    restart: always
    ports:
      - "8070:8080"
  
  synapse_livekit:
    image: livekit/livekit-server:latest
    container_name: synapse_livekit
    command: --config /etc/livekit.yaml
    networks:
      - synapse_network
    ports:
      - "7880:7880/tcp"
      - "7881:7881/tcp"
      - "50000-50100:50000-50100/udp"
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "5349:5349/tcp"
      - "5349:5349/udp"
      - "52000-52100:52000-52100/udp"
    restart: always
    volumes:
      - ./livekit-config.yaml:/etc/livekit.yaml:ro
      - /home/app/synapse_chat/nginx/certbot/live/family.guilledev.com/:/certs

  synapse_db:
    image: postgres:14-alpine
    container_name: synapse_db
    restart: always
    networks:
      - synapse_network
    environment:
      - POSTGRES_USER=${SYNAPSE_DB_USER}
      - POSTGRES_PASSWORD=${SYNAPSE_DB_PASSWORD}
      - POSTGRES_DB=${SYNAPSE_DB_NAME}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ${SYNAPSE_DB_PATH}:/var/lib/postgresql/data

  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse_chat
    restart: always
    networks:
      - synapse_network
    depends_on:
      - synapse_db
      - synapse_jwt
      - synapse_livekit
    ports:
      - "127.0.0.1:8008:8008"
    volumes:
      - ${SYNAPSE_DATA_PATH}:/data
      - ./homeserver.yaml:/data/homeserver.yaml
    environment:
      - SYNAPSE_SERVER_NAME=family-server.guilledev.com
      - SYNAPSE_REPORT_STATS=no

  synapse_web:
    image: vectorim/element-web:latest
    container_name: synapse_web
    restart: always
    depends_on:
      - synapse
    networks:
      - synapse_network
    ports:
      - "127.0.0.1:9271:80"
    volumes:
      - ./element-config.json:/app/config.json

networks:
  synapse_network:
